#!/usr/bin/zsh

alias ec='emacsclient -a ""'
alias enw='emacs -nw'
alias er='systemctl --user restart emacs.service'
alias edaemon='nohup emacs --daemon >/dev/null &'

function e {
  nohup emacsclient --create-frame ${@} >/dev/null &
}
