#!/usr/bin/zsh

alias ec='emacsclient -a ""'
alias enw='emacs -nw'
alias er='systemctl --user restart emacs.service'
alias edaemon='emacs --daemon -n'

function e {
  emacsclient --create-frame ${@} -n
}
