#!/usr/bin/zsh

function kb {
  context="$1"
  shift
  for i
  do
     kubectl --context=$context scale --replicas=0 deployment/$i
     kubectl --context=$context scale --replicas=1 deployment/$i
  done
  #clicache -del kubectl --context=$context get pod --no-headers
}

function ki {
  #clicache kubectl --context=$1 get pod -l "app=$2" --no-headers | cut -d ' ' -f1
  echo -n "$1 "
  kubectl --context=$1 get pod --no-headers | grep $2 | head -1| cut -d ' ' -f1
}

function kcc {
  rm -rf ~/.cache/clicache/*
}

function k {
  kubectl --context=$1 ${@:2}
}

function kp {
  kubectl --context=$1 get pod ${@:2}
}

function kpn {
  kubectl --context=$1 get pod -o jsonpath='{range .items[*]}{.metadata.name}{"\n"}{end}' ${@:2}
}

function kga {
  kubectl --context=$1 get pod -l "app=${@:2}" --no-headers
}

function kw {
  watch kubectl --context=$1 get pod
}

function kbw {
  kb ${@:1}
  kw ${@:1}
}

function kx {
  kubectl --context=$1 exec -it $2 -- ${@:3}
}

function kl {
  kubectl --context=$1 log ${@:2}
}

function ka {
  kubectl --context=$1 apply -f ${@:2}
}

function kr {
  kubectl --context=$1 replace --cascade --force -f ${@:2}
}

function kpf {
  kubectl --context=$1 port-forward ${@:2}
}

function kp {
  kubectl --context=$1 patch deployment $2 -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"redeployTimestamp\": \"$(date -u -R)\"}}}}}"
}
