#!/bin/bash

# pullmepushyou
function pmpy {
	if git diff --quiet; then
		git pull
	else
		git add .
		git commit -m "pmpy"
		git pull
		git push
	fi
}

function pmpy_all {
	dirs=(~/dotfiles)
	for d in "${dirs[@]}"; do
		pushd "$d"
		pmpy
		popd
	done

}
