#!/bin/bash

# pullmepushyou
function pmpy {
	d="$1"
	if [ "$d" = "" ]; then
		d="."
	fi
	echo "$d"
	pushd "$d"
	if git diff --quiet HEAD; then
		git pull
		git push
	else
		git add .
		git commit -m "pmpy"
		git pull
		git push
	fi
	popd
}

function pmpy_all {
	dirs=(~/dotfiles ~/movio-dotfiles)
	for d in "${dirs[@]}"; do
		pmpy "$d"
	done

}
